### ISSUE TITLE
python scripts/gen_repre.py --opts-path configs/gen_repre/lmo.json issue

### ISSUE THREAD

**Issue by AntonAgafonovbsch** [facebookresearch/foundpose#7]
Great paper. 
Trying to run the repo. 

In python scripts/gen_repre.py --opts-path configs/gen_repre/lmo.json I encounter following error:

I1104 11:01:21.356 1284736 loader.py:74] Loading faiss with AVX512 support.
I1104 11:01:21.447 1284736 loader.py:76] Successfully loaded faiss with AVX512 support.
Object Lids:  [1, 5, 6, 8, 9, 10, 11, 12]
W1104 11:01:22.247 1284736 _cpp_lib.py:133] WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 1.13.1)
    Python  3.9.16 (you have 3.9.20)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
/media/aga1tv/data_2nd_disk/GitHub/foundpose/external/dinov2/dinov2/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/media/aga1tv/data_2nd_disk/GitHub/foundpose/external/dinov2/dinov2/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/media/aga1tv/data_2nd_disk/GitHub/foundpose/external/dinov2/dinov2/layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
I1104 11:01:22.290 1284736 vision_transformer.py:122] using MLP layer as FFN
Device:  cpu
I1104 11:01:22.785 1284736 misc.py:41] Time for preparation: 0.00204s
I1104 11:01:22.802 1284736 gen_repre.py:112] Processing dataset 0/798, 
Traceback (most recent call last):
  File "/media/aga1tv/data_2nd_disk/GitHub/foundpose/scripts/gen_repre.py", line 413, in <module>
    main()
  File "/media/aga1tv/data_2nd_disk/GitHub/foundpose/scripts/gen_repre.py", line 407, in main
    generate_repre_from_list(
  File "/media/aga1tv/data_2nd_disk/GitHub/foundpose/scripts/gen_repre.py", line 403, in generate_repre_from_list
    generate_repre(opts, opts.object_dataset, object_lid, device, extractor)
  File "/media/aga1tv/data_2nd_disk/GitHub/foundpose/scripts/gen_repre.py", line 260, in generate_repre
    repre = generate_raw_repre(
  File "/media/aga1tv/data_2nd_disk/GitHub/foundpose/scripts/gen_repre.py", line 172, in generate_raw_repre
    ) = feature_util.get_visual_features_registered_in_3d(
  File "/media/aga1tv/data_2nd_disk/GitHub/foundpose/utils/feature_util.py", line 185, in get_visual_features_registered_in_3d
    kornia.morphology.erosion(
TypeError: squeeze() received an invalid combination of arguments - got (list), but expected one of:
 * ()
      didn't match because some of the arguments have invalid types: (list)
 * (int dim)
      didn't match because some of the arguments have invalid types: (list)
 * (name dim)
      didn't match because some of the arguments have invalid types: (list)

Somebody know how to solve this?

Thanks

**Comment by evinpinar** [comment]
Please double-check your installation since it looks like Pytorch is not running in Cuda, which might be triggering an error from the Kornia side as well. Then make sure the input to the erosion function is given as expected (mask and kernel size and their locations).
